vim.lsp.config("gopls", {
	cmd = { "gopls" },
	filetypes = { "go", "gomod" },
	root_markers = { "go.mod", ".git" },
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
				shadow = false,
				ST1000 = false,
				QF1001 = true,
				QF1007 = true,
				S1000 = true,
				S1001 = true,
				S1002 = true,
				S1005 = true,
				S1007 = true,
				S1008 = true,
				S1009 = true,
				S1016 = true,
				S1017 = true,
				S1021 = true,
				SA1000 = true,
				SA1001 = true,
				SA1002 = true,
				SA1007 = true,
				SA1010 = true,
			},
			staticcheck = true,
			gofumpt = true,
			hints = {
				rangeVariableTypes = true,
				parameterNames = true,
				constantValues = true,
				assignVariableTypes = true,
				compositeLiteralFields = true,
				compositeLiteralTypes = true,
				functionTypeParameters = true,
			},
		},
	},
})
