require("nvim-treesitter.install").prefer_git = true
require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"c",
		"cmake",
		"elixir",
		"erlang",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"go",
		"gomod",
		"gosum",
		"gotmpl",
		"gpg",
		"helm",
		"html",
		"java",
		"javascript",
		"jq",
		"json",
		"json5",
		"kotlin",
		"lua",
		"luadoc",
		"make",
		"markdown",
		"markdown_inline",
		"nginx",
		"php",
		"python",
		"r",
		"regex",
		"rust",
		"scala",
		"sql",
		"ssh_config",
		"svelte",
		"terraform",
		"toml",
		"toml",
		"vim",
		"vimdoc",
		"vue",
		"yaml",
	},
	sync_install = false,
	auto_install = false,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
	endwise = {
		enable = true,
	},
	textobjects = {
		select = {
			enable = true,
			lookahead = true,
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["ac"] = "@class.outer",
				["ic"] = { query = "@class.inner", desc = "Select inner part of a class region" },
			},
			include_surrounding_whitespace = true,
		},
	},
})
